Feature/sopriko kafka 2
c0dehuntjar3d/JavaSchool pull request #2
Opened 2024-12-25 14:19 UTC by c0dehuntjar3d

Соприко Даниил Сергеевич. Задание 2

2024-12-27 21:11 UTC, Liman26 requested changes

2024-12-27 21:11 UTC, Liman26 commented on src/main/java/sbp/school/kafka/config/KafkaProperties.java
> +            appProps.put("max.poll.interval.ms", "300000"); // 5 минут
Почему параметры хардкодом?

2024-12-27 21:11 UTC, Liman26 commented on src/main/java/sbp/school/kafka/properties/loader/PropertiesLoader.java
> +        inputStream.close();
ресурсы надо закрывать в try finally

2024-12-27 21:11 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/transaction/TransactionProducerService.java
> +        producer.close();
close уже содержит в себе flush

2024-12-27 21:11 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/transaction/TransactionProducerService.java
> +            log.error("error sending message to {}: {}", transactionTopic, transaction);
само исключение почему не логируем?

2024-12-27 21:11 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/transaction/TransactionConsumerService.java
> +            log.error(
В этом случае асинхронный коммит возможно не успеет все сообщения закомитить...

2024-12-28 16:04 UTC, c0dehuntjar3d commented on src/main/java/sbp/school/kafka/config/KafkaProperties.java
> +            appProps.put("max.poll.interval.ms", "300000"); // 5 минут
исправлено

2024-12-28 16:04 UTC, c0dehuntjar3d commented on src/main/java/sbp/school/kafka/properties/loader/PropertiesLoader.java
> +        inputStream.close();
исправлено

2024-12-28 16:04 UTC, c0dehuntjar3d commented on src/main/java/sbp/school/kafka/service/transaction/TransactionProducerService.java
> +        producer.close();
исправлено

2024-12-28 16:05 UTC, c0dehuntjar3d commented on src/main/java/sbp/school/kafka/service/transaction/TransactionProducerService.java
> +            log.error("error sending message to {}: {}", transactionTopic, transaction);
исправлено

2024-12-28 18:39 UTC, c0dehuntjar3d commented on src/main/java/sbp/school/kafka/config/KafkaProperties.java
> +            appProps.put("max.poll.interval.ms", "300000"); // 5 минут
исправлено

2024-12-28 18:39 UTC, c0dehuntjar3d commented on src/main/java/sbp/school/kafka/properties/loader/PropertiesLoader.java
> +        inputStream.close();
исправлено

2024-12-28 18:39 UTC, c0dehuntjar3d commented on src/main/java/sbp/school/kafka/service/transaction/TransactionProducerService.java
> +        producer.close();
исправлено

2024-12-28 18:39 UTC, c0dehuntjar3d commented on src/main/java/sbp/school/kafka/service/transaction/TransactionProducerService.java
> +            log.error("error sending message to {}: {}", transactionTopic, transaction);
исправлено

2024-12-28 18:40 UTC, c0dehuntjar3d commented on src/main/java/sbp/school/kafka/service/transaction/TransactionConsumerService.java
> +            log.error(
исправлено

2025-01-03 06:01 UTC, Liman26 approved these changes

2025-01-03 07:44 UTC, merged